Added more details to README.md
Black-Boys-Code/TicTacToe pull request #2
Opened 2022-10-09 00:33 UTC by MisterUmba

Added more details that shines a light on what this project is about.

2022-10-11 16:27 UTC, delisma requested changes

2022-10-11 16:27 UTC, delisma commented on README.md
> +This project was build for the black boys code organization. It's intetions is to be used for teaching fundamental ideas in building a website.
```suggestion
This project was build for the Black Boys Code organization. Its intentions is to be used for teaching fundamental ideas in building a website. 
```

2022-10-11 16:27 UTC, delisma commented on README.md
> +Very simple. Open the index.html page in your browser.
```suggestion
Very simple, go to [](https://black-boys-code.github.io/TicTacToe). Or open this repo in Glitch project.
)```

2022-10-11 16:27 UTC, delisma commented on README.md
> +Students learning the basics of web development.
```suggestion
Black Boys Code students learning the basics of web development. 
```

2023-04-21 23:43 UTC, MisterUmba commented
I've made all the requested changes.

2023-04-21 23:43 UTC, merged